version: '3.9'

services:
  nginx:
    image: nginx:1.23
    container_name: ${APP_NAME}_nginx
    ports:
      - '80:80'
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - ./../src:/var/www/html
      - ./storage/nginx/logs:/var/log/nginx
      - ./images/nginx/default-local.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: ./images/php-fpm
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php_fpm
    ports:
      - '8080:8080'
    volumes:
      - ./../src:/var/www/html
      - ./images/php-fpm/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: UTC
    cap_add:
      - SYS_NICE

  node:
    image: node:18.6
    container_name: ${APP_NAME}_node
    ports:
      - '3000:3000'
    expose:
      - 3000
    volumes:
      - ./../src:/var/www/html
    working_dir: /var/www/html
    tty: true
